name: mavental
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  equatable: ^2.0.5
  logger: ^2.0.1
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  environment_config: ^3.1.0
  url_launcher: ^6.1.12
  formz: ^0.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  intl: ^0.18.0
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  validators: ^3.0.0

  # WIDGET
  photo_view: ^0.14.0
  modal_bottom_sheet: ^3.0.0-pre
  bot_toast: ^4.0.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  scrollable_positioned_list: ^0.3.8
  webview_flutter: ^4.2.2

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  go_router: ^10.0.0
  get_it: ^7.6.0

  # FIREBASE
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  # firebase_app_check: ^0.1.4+1
  firebase_crashlytics: ^3.3.4
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  firebase_messaging: ^14.6.5
  cloud_firestore: ^4.8.4
  # flutter_local_notifications: ^12.0.4
  # flutter_app_badger: ^1.5.0
  # firebase_dynamic_links: ^5.0.8
  # flutter_facebook_auth: ^5.0.6
  # sign_in_with_apple: ^4.2.0
  # uni_links: ^0.5.1
  # firebase_remote_config: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.0
  freezed: ^2.3.2
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/images/
    - assets/images/locale/
    - assets/lotties/
    - assets/svgs/
