// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLqjBobFKJ3hgv7xvfRPz-7zANVIiEJAA',
    appId: '1:158898518103:web:ca99e08b483da37a544b12',
    messagingSenderId: '158898518103',
    projectId: 'goldenowl-mavental',
    authDomain: 'goldenowl-mavental.firebaseapp.com',
    storageBucket: 'goldenowl-mavental.appspot.com',
    measurementId: 'G-GPCSCZWRWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtxnrphBRcXdq0oJjemEEE78Z5BHACyo',
    appId: '1:158898518103:android:602b97bcd2004f67544b12',
    messagingSenderId: '158898518103',
    projectId: 'goldenowl-mavental',
    storageBucket: 'goldenowl-mavental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjnIWoGH8Sa8utPPtfajtJem62j4638o',
    appId: '1:158898518103:ios:2c737ce0f0bfc99a544b12',
    messagingSenderId: '158898518103',
    projectId: 'goldenowl-mavental',
    storageBucket: 'goldenowl-mavental.appspot.com',
    iosClientId: '158898518103-rv59ka5ujeobf117h8s35ga60e2da6tn.apps.googleusercontent.com',
    iosBundleId: 'com.maverick.go.mavental.stg',
  );
}
